### PR TITLE
add smartcheck tool

### PR DESCRIPTION
**Pull request by eMarchenko**
Added SmartCheck to list of linters

### CODE REVIEW

**Review by fubuloubu — APPROVED** [review]

**Comment by eMarchenko** [comment]
Hi Bryant! could you please merge `tools-list` branch into `master`, as this PR was to the `tools-list` branch?

**Comment by fubuloubu** [comment]
Whoops, fixed. Sorry I screwed that up!

**Comment by fubuloubu** [comment]
Also, that's awesome that you support Vyper! First static analyzer to do so!!

**Comment by eMarchenko** [comment]
well, actually Vyper is coming in couple of days, but hope it's fine )

**Pull request merged**
